package smithy4s.zio.examples.zschema

import smithy4s.Schema
import smithy4s.zio.schema._
import zio._
import zio.schema.codec.{BinaryCodec, JsonCodec, ProtobufCodec}
import zio.schema.{Schema => ZSchema}

/** Example showing how to convert smithy4s schemas to ZIO Schemas
  * and use them with ZIO Schema codecs (JSON, Protobuf, etc.)
  *
  * This enables smithy4s-generated types to access the ZIO Schema ecosystem:
  * - Binary codecs (Protobuf, Avro, Thrift, MessagePack)
  * - JSON codec integration
  * - Schema validation
  * - Schema migrations
  * - Schema diffing and pretty printing
  */
object ZSchemaExample extends ZIOAppDefault {

  // Example data model
  case class Person(name: String, age: Int, email: Option[String])

  object Person {
    // This would typically be generated by smithy4s from your .smithy files
    val smithy4sSchema: Schema[Person] = {
      import smithy4s.schema.Schema._
      val nameField = string.required[Person]("name", _.name)
      val ageField = int.required[Person]("age", _.age)
      val emailField = string.optional[Person]("email", _.email)
      struct(nameField, ageField, emailField)(Person.apply)
    }

    // Convert to ZIO Schema using the extension method
    implicit val zioSchema: ZSchema[Person] = smithy4sSchema.toZSchema

    // Derive codecs from the ZIO Schema
    val jsonCodec: BinaryCodec[Person] = JsonCodec.schemaBasedBinaryCodec(zioSchema)
    val protobufCodec: BinaryCodec[Person] = ProtobufCodec.protobufCodec(zioSchema)
  }

  override def run: ZIO[Any, Throwable, Unit] = {
    for {
      _ <- Console.printLine("=== ZIO Schema Integration Example ===\n")

      // Create a test person
      person = Person("Alice", 30, Some("alice@example.com"))
      _ <- Console.printLine(s"Original person: $person\n")

      // === JSON Codec Example ===
      _ <- Console.printLine("--- JSON Codec ---")
      jsonBytes = Person.jsonCodec.encode(person)
      jsonString = new String(jsonBytes.toArray, "UTF-8")
      _ <- Console.printLine(s"Encoded JSON: $jsonString")

      decodedFromJson <- ZIO
        .fromEither(Person.jsonCodec.decode(jsonBytes))
        .mapError(error => new Exception(s"JSON decode failed: $error"))
      _ <- Console.printLine(s"Decoded from JSON: $decodedFromJson")
      _ <- Console.printLine(s"JSON roundtrip successful: ${person == decodedFromJson}\n")

      // === Protobuf Codec Example ===
      _ <- Console.printLine("--- Protobuf Codec ---")
      protobufBytes = Person.protobufCodec.encode(person)
      _ <- Console.printLine(
        s"Encoded Protobuf (${protobufBytes.size} bytes): ${protobufBytes.toArray.take(20).mkString("[", ", ", "...]")}"
      )

      decodedFromProtobuf <- ZIO
        .fromEither(Person.protobufCodec.decode(protobufBytes))
        .mapError(error => new Exception(s"Protobuf decode failed: $error"))
      _ <- Console.printLine(s"Decoded from Protobuf: $decodedFromProtobuf")
      _ <- Console.printLine(
        s"Protobuf roundtrip successful: ${person == decodedFromProtobuf}\n"
      )

      // === Schema Introspection ===
      _ <- Console.printLine("--- Schema Introspection ---")
      _ <- Console.printLine(s"ZIO Schema type: ${Person.zioSchema}")
      _ <- Console.printLine(
        s"Can be used with: Avro, Thrift, MessagePack, and other ZIO Schema codecs\n"
      )

      // === Complex Example with Collections ===
      _ <- Console.printLine("--- Collections Example ---")
      people = List(
        Person("Alice", 30, Some("alice@example.com")),
        Person("Bob", 25, None),
        Person("Charlie", 35, Some("charlie@example.com"))
      )
      _ <- Console.printLine(s"People list: $people")

      // Create schema and codec for list of people
      peopleListSchema = Schema.list(Person.smithy4sSchema).toZSchema
      peopleListCodec = JsonCodec.schemaBasedBinaryCodec(peopleListSchema)
      peopleJson = peopleListCodec.encode(people)
      peopleJsonString = new String(peopleJson.toArray, "UTF-8")
      _ <- Console.printLine(s"Encoded list as JSON: $peopleJsonString")

      _ <- Console.printLine("\n=== Example Complete ===")
      _ <- Console.printLine(
        "You can now use any smithy4s-generated schema with ZIO Schema codecs!"
      )

    } yield ()
  }
}
